name: Build APK Admin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
      - run: |
          gradle wrapper --gradle-version 8.5
          ./gradlew assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: app-admin-debug
          path: app/build/outputs/apk/debug/*.apk
